name: Node.js CI

on: [push]

defaults:
    run:
        working-directory: ./keep.js

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.11.x'
    - run: npm ci
    - run: npm run lint:js
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
